version: '3.7'
services:
  postgresdb:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    volumes:
      - /data:/docker-entrypoint-initdb.d